name: dart_ffi_bindings_generator
description: Generate FFI bindings for Dart directly from C header files
version: 0.0.1
homepage: https://github.com/mannprerak2/dart_ffi_bindings_generator

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ffi_tool: ^0.2.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
